apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: myserverlesssub
  namespace: openshift-operators 
spec:
  channel: stable 
  name: serverless-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
